<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>
    <parent>
        <groupId>com.zhoouon</groupId>
        <artifactId>zhoouon-samples</artifactId>
        <version>${revision}</version>
    </parent>
    <artifactId>zhoouon-starter</artifactId>
    <description>公共组件模块</description>
    <packaging>pom</packaging>

    <properties>
        <java.version>17</java.version>
    </properties>

    <modules>
        <module>zhoouon-logging-spring-boot-starter</module>
        <module>zhoouon-id-spring-boot-starter</module>
        <module>zhoouon-datasource-spring-boot-starter</module>
        <module>zhoouon-common-spring-boot-starter</module>
        <module>zhoouon-openfeign-spring-boot-starter</module>
        <module>zhoouon-web-spring-boot-starter</module>
        <module>zhoouon-rocketmq-spring-boot-starter</module>
        <module>zhoouon-core-spring-boot-starter</module>
        <module>zhoouon-monitor-spring-boot-starter</module>
    </modules>

    <dependencyManagement>
        <dependencies>
            <dependency>
                <groupId>com.zhoouon</groupId>
                <artifactId>zhoouon-dependencies</artifactId>
                <version>${revision}</version>
                <type>pom</type>
                <scope>import</scope>
            </dependency>
        </dependencies>
    </dependencyManagement>
</project>
