#\u4E8B\u52A1\u4F1A\u8BDD\u4FE1\u606F\u5B58\u50A8\u65B9\u5F0F
store.mode=db
#\u4E8B\u52A1\u9501\u4FE1\u606F\u5B58\u50A8\u65B9\u5F0F
store.lock.mode=db
#\u4E8B\u52A1\u56DE\u8BDD\u4FE1\u606F\u5B58\u50A8\u65B9\u5F0F
store.session.mode=db

#\u5B58\u50A8\u65B9\u5F0F\u4E3Adb
store.db.dbType=mysql
store.db.datasource=druid
store.db.driverClassName=com.mysql.cj.jdbc.Driver
# \u4E0B\u65B9\u4F60\u7684\u6570\u636E\u5E93\u540D\u79F0\u5982\u679C\u4E0D\u662F seata \u8BB0\u5F97\u4FEE\u6B63
store.db.url=jdbc:mysql://host.docker.internal:3306/seata?useUnicode=true&serverTimezone=UTC
store.db.user=root
store.db.password=123456
store.db.minConn=5
store.db.maxConn=30
store.db.queryLimit=100
store.db.maxWait=5000
# \u4E0B\u9762 4 \u9879\u5BF9\u5E94\u7684\u6570\u636E\u5E93\u4E2D\u51E0\u5F20\u6570\u636E\u8868
store.db.globalTable=global_table
store.db.branchTable=branch_table
store.db.lockTable=lock_table
store.db.distributedLockTable=distributed_lock
service.vgroupMapping.default_tx_group=default
service.default.grouplist=127.0.0.1:18091
